### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by monfresh**
Includes many optimizations.

### CODE REVIEW

**Comment by monfresh** [comment]
@anselmbradford, when you get a chance, could you please look over this and fix the issue with the map markers? The map is only showing the "Other" marker, and I wasn't sure how to get the markers in `markers.js.erb` to work with the new map modules you created in the upstream repo. Also, there are some JS lint errors in some of the SMC-specific JS files, like `term-popup-manager.js`. Thanks!

**Comment by monfresh** [comment]
Hi @anselmbradford. Just checking to see when you'll be able to take a look at this. Thanks!

**Comment by anselmbradford** [comment]
Oops, sorry I overlooked this! I'll check tonight.

**Comment by anselmbradford** [comment]
@monfresh Check it out!

**Comment by monfresh** [comment]
@anselmbradford Thanks! Will check it out today.

**Comment by monfresh** [comment]
@anselmbradford, I don't see the "Update search results" alert anymore. Did you remove it, or perhaps when I fixed conflicts, I messed it up?

**Comment by monfresh** [comment]
@anselmbradford Figured it out. I had remove `app/alerts` from `search_filters.js`, but I put it back in and it works now.

**Pull request merged**
