### PR TITLE
Adds touch icons and templates

### PR DESCRIPTION
**Pull request by anselmbradford**
- Adds SMC-specific touch icons.
- Adds generic graphic templates per those added in
https://github.com/codeforamerica/ohana-web-search/pull/779.
SMC-specific template files can’t be added because SMC logo uses
proprietary fonts.

### CODE REVIEW

**Comment by anselmbradford** [comment]
@monfresh Ready for merge. This is identical to https://github.com/codeforamerica/ohana-web-search/pull/779, except the generated touch icons are SMC-specific. Unfortunately we can't provide SMC-specific templates in the repo because the fonts are proprietary.

**Comment by anselmbradford** [comment]
Oops, hold on one sec, accidentally have "web search" instead of "connect" in the icons.

**Comment by monfresh** [comment]
You da man! Thanks, but I think the icon should say SMC Connect, not Web Search, since that's the name people know the site by.

**Comment by monfresh** [comment]
ha. jinx

**Comment by anselmbradford** [comment]
Updated!

**Comment by monfresh** [comment]
Looks good, thanks! Merging now.

**Pull request merged**
